DROP TABLE IF EXISTS USER;
CREATE TABLE USER
(
    id    BIGINT(20)  NOT NULL COMMENT '主键ID',
    NAME  VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    age   INT(11)     NULL DEFAULT NULL COMMENT '年龄',
    email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    PRIMARY KEY (id)
);